#!/bin/bash

modprobe vfio-pci

for dev in "$@"; do
	current_override=$(cat /sys/bus/pci/devices/$dev/driver_override)
	vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
	echo "===> VFIO "
	echo "==="
	echo "$current_override"
#	echo "Resetting Device"
#	echo -n 1 > /sys/bus/pci/devices/$dev/reset
	if [ "$current_override" = "vfio-pci" ]; then
		echo -n "$vendor $device" > /sys/bus/pci/drivers/vfio-pci/new_id
		echo $dev allready claimed
		continue
	fi

	echo "Binding $dev"
	dir="/sys/bus/pci/devices/$dev"
	if [ ! -d "$dir" ];then
		echo "Nonexisting device $dev"
	fi

        if [ -d "$dir/driver" && -e "$dir/driver/unbind" ]; then
                echo -e -n "$dev" > "$dir/driver/unbind"
        fi
	echo "Overriding Driver"
	echo -e -n "vfio-pci" > /sys/bus/pci/devices/$dev/driver_override
        sleep 1
	echo -n "$vendor $device" > /sys/bus/pci/drivers/vfio-pci/new_id
done
#echo 1b73 1100 > /sys/bus/pci/drivers/vfio-pci/new_id
#echo 1002 679a >  /sys/bus/pci/drivers/vfio-pci/new_id
#echo 1002 aaa0 > /sys/bus/pci/drivers/vfio-pci/new_id
