#!/bin/bash

if [ "x$TERADICI_PCI" != "x" ]; then 

RUN_PRE_BOOT+=(
vfio-bind 0000:${TERADICI_PCI}.0
vfio-bind 0000:${TERADICI_PCI}.1
vfio-bind 0000:${TERADICI_PCI}.2
vfio-bind 0000:${TERADICI_PCI}.3
vfio-bind 0000:${TERADICI_PCI}.4
)

QEMU_OPTS+=( 
-device vfio-pci,host=$TERADICI_PCI.0,bus=pcie.5,addr=0.0,multifunction=on
-device vfio-pci,host=$TERADICI_PCI.1,bus=pcie.5,addr=0.1
-device vfio-pci,host=$TERADICI_PCI.2,bus=pcie.5,addr=0.2
-device vfio-pci,host=$TERADICI_PCI.3,bus=pcie.5,addr=0.3
-device vfio-pci,host=$TERADICI_PCI.4,bus=pcie.5,addr=0.4
)

echo "Using Teradici Controller:"
lspci -s "$TERADICI_PCI"

fi
